### ISSUE TITLE
Update-MsIdInvitedUserSponsorsFromInvitedBy

### ISSUE THREAD

**Issue by thomasforde** [AzureAD/MSIdentityTools#61]
when running with -All mode i get the following error. 

Get-MgUser_List: Unsupported or invalid query filter clause specified for property 'creationType' of resource 'User'.  Status: 400 (BadRequest) ErrorCode: Request_UnsupportedQuery

When running with a single -userid
Update-MsIdInvitedUserSponsorsFromInvitedBy -UserId 37cf98b7-063a-4783-b689-f6b25f041b86
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 2.
PropertyNotFoundException: The property 'Sponsors' cannot be found on this object. Verify that the property exists.

i do see the sponsors on the object and can manually add this from EntraID

powershell 7 and all modules install just prior to attempting this command.

**Comment by albert-widjaja** [comment]
Yes, I get the same error too.
Using the https://www.powershellgallery.com/packages/MSIdentityTools/2.0.68 and pwsh v7.4.4

```
PS C:\> Update-MsIdInvitedUserSponsorsFromInvitedBy -All -WhatIf
Get-MgUser_List: Unsupported or invalid query filter clause specified for property 'creationType' of resource 'User'.  Status: 400 (BadRequest) ErrorCode: Request_UnsupportedQuery Date:PS C:\> Update-MsIdInvitedUserSponsorsFromInvitedBy -All -WhatIf
Get-MgUser_List: Unsupported or invalid query filter clause specified for property 'creationType' of resource 'User'.  Status: 400 (BadRequest) ErrorCode: Request_UnsupportedQuery Date:
```

**Comment by merill** [comment]
Thanks for the patience folks. This has been fixed. 

Please update to the latest version. Tx.

**Comment by thomasforde** [comment]
I do still get the 2nd error after update. 

PropertyNotFoundException: The property 'Sponsors' cannot be found on this object. Verify that the property exists.

When i check the guests account i can see the sponsors property on the object and can manually add this from EntraID

**Comment by ppolkadots** [comment]
Hi @thomasforde, do you mind opening a support ticket and sharing it here please? I tried to replicate this but wasn't successful. We will need additional details like timestamp of your error to debug this. Thanks!

**Comment by thomasforde** [comment]
where do you want me to open a ticket? i tried running the command again now and i get the  same error.

**Comment by thomasforde** [comment]
I did upgrade to 2.0.70 to be able to fix the first bug, which was the typo error.

the second bug with the "_PropertyNotFoundException: The property 'Sponsors' cannot be found on this object. Verify that the property exists_" wasnt fix, and is still there.

Some users i get "_the invited user information not available for this user_", but last attempt generated about 600 lines of this error, which i assume has something to do with the entra id user and the script or something. since not all users generate this error.

**Comment by ppolkadots** [comment]
Here's how you can raise support ticket: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by SuryenduB** [comment]
It works when you Import the module

**Comment by thomasforde** [comment]
@ppolkadots there are like 1000 options, and issues, and some dont allow me to raise a ticket or have some solutions available instead, and its cumbersome to try and move past this, to get to a point where i can actually register a ticket. I need details from you as to what choices i need to select to move forward to get the case registerd in the proper place with the proper service, problem type and subtype etc....

when you have one portal to rule them all, the portal gets too big with too many choices...:)

**Comment by SuryenduB** [comment]
@thomasforde Hi Thomas, did you try to explicitly import the module, in your script? I had the similar error and importing the module fixed it for me.

**Comment by ppolkadots** [comment]
@thomasforde please try the recommendation above. Keep us posted!

**Comment by ppolkadots** [comment]
You can raise a ticket through Azure portal - support blade: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by thomasforde** [comment]
I installed powershell 7.4.4 fresh.  i installed the module from the powershell gallery with the Install-Module command.
i again did the Import-Module. I verified with Get-InstalledModule that version 2.0.70 is installed. 

 i dont have any scripts, i run the command single line in powershell prompt, and it produce this error. 
but this is taking too much of my time to bother with it anymore. I dont have time to search through 1000 sections and suboptions to create a support ticket, or repeating myself here. I stated in the first entry that i ran the command, not scripts..

if you want more intel my twitter handle is on this profile..  you can close this bug.
